language: node_js
node_js:
  - "4"
  - "6"
group: bluezone
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run docs; fi
deploy:
  skip_cleanup: true
  provider: script
  script: sh scripts/deploy.sh
  on:
    branch: master
