language: node_js
node_js:
  - "4"
  - "6"
group: bluezone
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
deploy:
  provider: script
  script: sh travis.ci/deploy.sh
  on:
    all_branches: true
