language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run coverage
deploy:
  skip_cleanup: true
  provider: script
  script: sh scripts/deploy.sh
  on:
    branch: master
